on: [push, workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build the package
        run: npm pack

      - uses: actions/setup-node@v1
        with:
          scope: ${{ github.repository_owner }}
          registry-url: https://npm.pkg.github.com

      - name: Publish the package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
